"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

const GOAL_LABELS: Record<string, string> = {
  content_ideas: "Content Ideas",
  market_brief: "Market Brief",
  competitor_intel: "Competitor Intel",
};

interface ReportMeta {
  goal: string;
  generatedAt: string | null;
}

interface ReportDetail {
  goal: string;
  generatedAt: string;
  content: string;
}

export default function AgentReportsPage() {
  const [reports, setReports] = useState<ReportMeta[]>([]);
  const [loading, setLoading] = useState(true);
  const [viewing, setViewing] = useState<ReportDetail | null>(null);
  const [loadingReport, setLoadingReport] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/agents/reports")
      .then((res) => res.json())
      .then((data) => {
        setReports(data.reports ?? []);
      })
      .catch(() => setReports([]))
      .finally(() => setLoading(false));
  }, []);

  const handleView = async (goal: string) => {
    setLoadingReport(goal);
    try {
      const res = await fetch(`/api/agents/reports/${goal}`);
      if (!res.ok) throw new Error("Not found");
      const data: ReportDetail = await res.json();
      setViewing(data);
    } catch {
      setViewing(null);
    } finally {
      setLoadingReport(null);
    }
  };

  const formatDate = (iso: string | null) => {
    if (!iso) return "Never run";
    const d = new Date(iso);
    return d.toLocaleString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    });
  };

  if (viewing) {
    return (
      <div className="min-h-screen bg-white text-black">
        <header className="border-b border-gray-200 sticky top-0 z-10 bg-white">
          <div className="max-w-4xl mx-auto px-4 py-4">
            <Link
              href="/agents"
              className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-black mb-2"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Agent Reports
            </Link>
            <h1 className="text-xl font-bold">
              {GOAL_LABELS[viewing.goal] ?? viewing.goal}
            </h1>
            <p className="text-sm text-gray-500 mt-1">
              Generated: {formatDate(viewing.generatedAt)}
            </p>
          </div>
        </header>
        <main className="max-w-4xl mx-auto px-4 py-6">
          <div className="prose prose-sm max-w-none">
            <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed bg-gray-50 p-4 rounded-lg overflow-x-auto">
              {viewing.content}
            </pre>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white text-black">
      <header className="border-b border-gray-200 sticky top-0 z-10 bg-white">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-black mb-2"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Digest
          </Link>
          <h1 className="text-xl font-bold">Agent Reports</h1>
          <p className="text-sm text-gray-500 mt-1">
            Latest runs from the Content Ideas, Market Brief, and Competitor Intel
            agents. Reports are generated by the script or the API; this view
            shows the most recent output for each.
          </p>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-4 py-6">
        {loading ? (
          <p className="text-gray-500">Loading…</p>
        ) : (
          <ul className="space-y-4">
            {reports.map((r) => (
              <li
                key={r.goal}
                className="border border-gray-200 rounded-lg p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"
              >
                <div>
                  <h2 className="font-semibold">
                    {GOAL_LABELS[r.goal] ?? r.goal}
                  </h2>
                  <p className="text-sm text-gray-500 mt-1">
                    Last run: {formatDate(r.generatedAt)}
                  </p>
                </div>
                <button
                  onClick={() => handleView(r.goal)}
                  disabled={loadingReport !== null || !r.generatedAt}
                  className="px-4 py-2 rounded-md bg-black text-white text-sm font-medium hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {loadingReport === r.goal
                    ? "Loading…"
                    : r.generatedAt
                      ? "View report"
                      : "No report yet"}
                </button>
              </li>
            ))}
          </ul>
        )}
        {reports.length === 0 && !loading && (
          <p className="text-gray-500 mt-4">
            No reports found. Run{" "}
            <code className="bg-gray-100 px-1 rounded">
              npx tsx scripts/run-agent-reports.ts
            </code>{" "}
            to generate them.
          </p>
        )}
      </main>
    </div>
  );
}
