/**
 * POST /api/newsletter/pdf
 * Generate printable HTML for newsletter PDF export
 */

import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { html, title } = await request.json();

    if (!html) {
      return NextResponse.json(
        { error: "HTML content required" },
        { status: 400 }
      );
    }

    // Return HTML document optimized for printing to PDF
    const printableHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title || "Newsletter"}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      background: white;
    }
    
    article {
      max-width: 850px;
      margin: 0 auto;
      padding: 40px 30px;
    }
    
    h1 {
      font-size: 2.5em;
      margin-bottom: 0.5rem;
      color: #1a1a1a;
      page-break-after: avoid;
    }
    
    h2 {
      font-size: 1.5em;
      color: #1a1a1a;
      margin-top: 2rem;
      margin-bottom: 1rem;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 0.5rem;
      page-break-after: avoid;
    }
    
    h3 {
      font-size: 1.1em;
      color: #333;
      margin-top: 1.5rem;
      margin-bottom: 0.5rem;
      page-break-after: avoid;
    }
    
    p {
      margin-bottom: 1rem;
      line-height: 1.7;
    }
    
    ul, ol {
      margin-left: 2rem;
      margin-bottom: 1rem;
    }
    
    li {
      margin-bottom: 0.5rem;
      line-height: 1.7;
    }
    
    a {
      color: #0066cc;
      text-decoration: none;
    }
    
    a:hover {
      text-decoration: underline;
    }
    
    strong {
      font-weight: 600;
      color: #1a1a1a;
    }
    
    em {
      font-style: italic;
      color: #555;
    }
    
    blockquote {
      border-left: 4px solid #0066cc;
      padding-left: 1rem;
      margin: 1.5rem 0;
      color: #666;
      font-style: italic;
    }
    
    code {
      background: #f5f5f5;
      padding: 0.2em 0.4em;
      border-radius: 3px;
      font-family: 'Courier New', monospace;
      font-size: 0.9em;
    }
    
    pre {
      background: #f5f5f5;
      padding: 1rem;
      border-radius: 4px;
      overflow-x: auto;
      margin: 1rem 0;
      font-family: 'Courier New', monospace;
      font-size: 0.9em;
      line-height: 1.4;
    }
    
    hr {
      border: none;
      border-top: 1px solid #e5e7eb;
      margin: 2rem 0;
    }
    
    @media print {
      body {
        background: white;
        color: #333;
      }
      
      a {
        color: #0066cc;
      }
      
      h1, h2, h3 {
        page-break-after: avoid;
      }
      
      p, li {
        orphans: 3;
        widows: 3;
      }
      
      article {
        padding: 0;
      }
    }
  </style>
</head>
<body>
  ${html}
  <footer style="margin-top: 3rem; padding-top: 2rem; border-top: 1px solid #e5e7eb; font-size: 0.875em; color: #666; text-align: center;">
    <p>Generated by Code Intelligence Digest</p>
  </footer>
</body>
</html>`;

    return new NextResponse(printableHtml, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
      },
    });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "PDF generation failed" },
      { status: 500 }
    );
  }
}
